input {
  http {
    port => 8081
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "[service][name]" => "flash-sale-backend"
      "[deployment][environment]" => "local"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-flashsale-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
