CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'VND',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_products_name_trimmed
        CHECK (name = BTRIM(name) AND CHAR_LENGTH(name) BETWEEN 1 AND 120),
    CONSTRAINT ck_products_price_positive CHECK (price > 0),
    CONSTRAINT ck_products_currency_vnd CHECK (currency = 'VND')
);

CREATE TABLE inventories (
    product_id BIGINT PRIMARY KEY,
    available_quantity BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventories_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_inventories_available_quantity_non_negative
        CHECK (available_quantity >= 0)
);
