CREATE TABLE inventory_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity_delta BIGINT NOT NULL,
    reason VARCHAR(200) NOT NULL,
    resulting_available_quantity BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_adjustments_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_inventory_adjustments_delta_non_zero
        CHECK (quantity_delta <> 0),
    CONSTRAINT ck_inventory_adjustments_reason_length
        CHECK (CHAR_LENGTH(reason) BETWEEN 3 AND 200),
    CONSTRAINT ck_inventory_adjustments_result_non_negative
        CHECK (resulting_available_quantity >= 0)
);

CREATE INDEX ix_inventory_adjustments_product_created
    ON inventory_adjustments (product_id, created_at DESC, id DESC);
