CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(120) NOT NULL,
    quantity SMALLINT NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    total_amount NUMERIC(20, 2) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_orders_customer_idempotency_key
        UNIQUE (customer_id, idempotency_key),
    CONSTRAINT ck_orders_quantity CHECK (quantity BETWEEN 1 AND 5),
    CONSTRAINT ck_orders_unit_price_positive CHECK (unit_price > 0),
    CONSTRAINT ck_orders_currency_vnd CHECK (currency = 'VND'),
    CONSTRAINT ck_orders_total_amount_positive CHECK (total_amount > 0),
    CONSTRAINT ck_orders_idempotency_key_length
        CHECK (CHAR_LENGTH(idempotency_key) BETWEEN 8 AND 128)
);

CREATE INDEX ix_orders_product_created
    ON orders (product_id, created_at DESC, id DESC);

CREATE INDEX ix_orders_customer_created
    ON orders (customer_id, created_at DESC, id DESC);
