spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flashsale}
    username: ${DB_USERNAME:flashsale}
    password: ${DB_PASSWORD:flashsale}
  flyway:
    locations: classpath:db/migration,classpath:db/local
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest

app:
  outbox:
    publisher:
      enabled: true
