spring:
  application:
    name: flash-sale-backend
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  shutdown: graceful
